import * as React from 'react';
import Layout from "../../../components/layout";
import Banner from "../../../components/project-details/banner";
import Result from "../../../components/project-details/result";
import KeyFeatureAllIn from "../../../components/project-details/key-feature-all-in";
import AppDetailTechnologySlider from "../../../components/project-details/app-detail-technology-slider";
import {ASSETS} from "../../../components/common/images";
import KeyFeature from "../../../components/project-details/key-feature";
import PageNotFound from "../../404";
const Detail = (props) => {
    const { name } = props;

    const data = [
        {
            "name": "all-in",
            "data": {
                projectTitle: `A Journey to Comfortable <span>Language Learning!</span>`,
                projectImage: ASSETS.APPDETAILS.AllInProject,
                projectDescription: `Learn popular Modern Foreign Languages (MFL) and English as Additional Language (EAL).
        All-in offers access to resources and classroom tools that make it easier for professionals to deliver outstanding language lessons.
        It is a zero-effort package, full of fun, and is additive.`,
                technology: [
                    ASSETS.APPDETAILS.Aws,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.ElasticSearch,
                    ASSETS.APPDETAILS.SymfonyImg,
                ],
                resultDescription: "It is said that a good process produces good results! All-in wanted to create a website with resources and activities, helping people to learn MFL and EAL. Hence, team GeekyBones worked together, creating a feature-rich website, witnessing bright results. Wonders lie in learning foreign languages. So, don't limit yourself!",
                resultSlideList: [
                ASSETS.APPDETAILS.AllIn1,
                ASSETS.APPDETAILS.AllIn2,
                ASSETS.APPDETAILS.AllIn3,
                ASSETS.APPDETAILS.AllIn4,
                ASSETS.APPDETAILS.AllIn5,
                ],
                listText1: 'Select topic',
                listText2: 'Select class code (optional)',
                listText3: 'Selected subtopics/sections',
                listText4: 'Choose Languages',
                listText5: 'Select Date, Lesson Title & Learning Objective (optional)',
                listText6: 'Select topic',
                listText7: 'Select class code (optional)',
                listText8: 'Selected subtopics/sections',
                listText9: 'Choose Languages',
                metaTitle: 'All-In Project - Web Development Case Studies | GeekyBones',
                metaDescription: 'Get started on a journey to comfortable learning. Learn more about the All-in website development and challenges faced by the GeekyBones. ',
            },
        },
        {
            "name": "sports-gear-swag",
            "data": {
                projectTitle: `Custom Sports Apparels to Capture the Identity of your Brand`,
                projectImage: ASSETS.APPDETAILS.SportGearProject,
                projectDescription: `Sports Gear Swag (SGS) believes that people deserve high-quality sports gear and an effortless style. SGS crafts elite jerseys and team apparel for everyday life. Comfort is a priority that incorporates impeccable craftsmanship, and highest quality materials.
`,
                technology: [
                    ASSETS.APPDETAILS.FabricJs,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.MySql,
                    ASSETS.APPDETAILS.SymfonyImg,
                ],
                resultDescription: "The main aim of Sports Gear Swag was to offer seamless customer experience where they can get their customized apparels. Team GeekyBones incorporated the right technologies and ideas, helping the client to reach business goals through a successful shopping website.",
                resultSlideList: [
                    ASSETS.APPDETAILS.SportHome,
                    ASSETS.APPDETAILS.SportBasketball,
                    ASSETS.APPDETAILS.SportFootball,
                    ASSETS.APPDETAILS.SportVolleyball,
                    ASSETS.APPDETAILS.SportBaseball,
                ],
                listText1: 'Custom E-Commerce Integration: We built a seamless shopping experience with a custom e-commerce solution that supports a wide range of products, from activewear to sports equipment. The site’s intuitive navigation and powerful search capabilities ensure users can easily find what they’re looking for.',
                listText2: 'Responsive Design: Understanding the importance of accessibility, we developed a fully responsive design that delivers a consistent and optimized experience across all devices, from desktops to smartphones.',
                listText3: 'User Experience Optimization: We focused on creating a user-centric design that simplifies the shopping journey. From product discovery to checkout, every step was designed to be fast, efficient, and enjoyable.',
                listText4: 'Advanced Product Management: The backend is powered by a robust product management system, allowing the Sports Gear Swag team to easily update inventory, manage promotions, and analyze sales data.',
                listText5: 'SEO and Performance Tuning: To ensure high visibility and fast load times, we implemented advanced SEO strategies and performance optimizations. This approach has driven significant traffic growth and improved search engine rankings.',
                listText6: 'Several payment methods available',
                metaTitle: 'Sports Gear Swag - Web Development | GeekyBones Case Studies',
                metaDescription: 'Custom sports apparels capture the brand identity! Sports Gear Swag offers craftsmanship and quality through an online website created by GeekyBones.',
            },
        },
        {
            "name": "mav3rik",
            "data": {
                projectTitle: `Get Ready to Change your World with Mav3rik`,
                projectImage: ASSETS.APPDETAILS.MavrikProject,
                projectDescription: `Mav3rik simplifies complexities and makes your business or work shine! It offers compelling UX and UI designs, bespoke mobile and web apps, innovative cloud-based solutions and seamless salesforce deployment, including automation, analytics and artificial intelligence.
`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "The client had a vision of changing the world by impacting the organizations. Team GeekyBones helped the client to accomplish goals by creating a platform, solving the complexities of organizations.",
                resultSlideList: [
                ASSETS.APPDETAILS.MavrikHome,
                ASSETS.APPDETAILS.MavrikAbout,
                ASSETS.APPDETAILS.MavrikService,
                ASSETS.APPDETAILS.MavrikCase,
                ASSETS.APPDETAILS.MavrikContact,
                ],
                listText1: 'Seamless Salesforce deployment',
                listText2: 'Cloud-based solutions',
                listText3: 'Application development',
                listText4: 'User experience',
                metaTitle: 'Mav3rik Project - Web Development Case Studies | GeekyBones',
                metaDescription: 'Change the digital world with innovative solutions. The GeekyBones helped Mav3rik to solve the complexities and accomplish goals by creating a platform.',
               },
        },
        {
            "name": "auslankamatrimony",
            "data": {
                projectTitle: `Find your Soulmate in a Better Way!`,
                projectImage: ASSETS.APPDETAILS.AuslankmatrimonyProject,
                projectDescription: `The aim of https://www.auslankamatrimony.com.au/ website is to achieve maximum happy marriages by discovering and matching prospective Lanka brides and bridegrooms residing in Australia. 
`,
                technology: [
                    ASSETS.APPDETAILS.MySql,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.SymfonyImg,
                ],
                resultDescription: "The client wanted to build a website that caters to the matrimonial needs of Sri Lanka people in Australia. The aim was to bring smiles to people's faces by helping them discover the perfect life partner. Team GeekyBones successfully powered the client's vision by creating a safe and secure matrimonial website.",
                resultSlideList: [
                    ASSETS.APPDETAILS.AuslankamatrimonyWebsite1,
                    ASSETS.APPDETAILS.AuslankamatrimonyWebsite2,
                    ASSETS.APPDETAILS.AuslankamatrimonyWebsite3,
                    ASSETS.APPDETAILS.AuslankamatrimonyWebsite1,
                    ASSETS.APPDETAILS.AuslankamatrimonyWebsite2,
                    ASSETS.APPDETAILS.AuslankamatrimonyWebsite3,
                ],
                listText1: '100% confidential',
                listText2: 'Personalised service',
                listText3: 'Reasonable membership fees',
                listText4: 'Easy registration process',
                metaTitle: 'Auslankamatrimony - Web Development Case Studies | GeekyBones',
                metaDescription: "The website www.auslankamatrimony.com.au helps in finding the perfect match. GeekyBones powered the client's vision by creating a matrimonial website.",
            },
        },
        {
            "name": "freshy-helpline",
            "data": {
                projectTitle: `We Help you Make Easy Adjustments to Your New Life`,
                projectImage: ASSETS.APPDETAILS.FreshyProject,
                projectDescription: `Moving to a new place can be stressful where you need accommodation, jobs, vehicles, etc. Freshy Helpline in Melbourne supports newcomers, especially International students from various communities with basic needs.`,
                technology: [
                    ASSETS.APPDETAILS.NodeJsImg,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.SymfonyImg,
                ],
                resultDescription: "The client wanted to build an online website and mobile app to help people from different communities in Melbourne through ads. The experts at GeekyBones mixed the creative ideas and right tech approach to fulfill client ideas successfully. ",
                resultSlideList: [
                    ASSETS.APPDETAILS.Freshy1,
                    ASSETS.APPDETAILS.Freshy2,
                    ASSETS.APPDETAILS.Freshy3,
                    ASSETS.APPDETAILS.Freshy4,
                ],
                listText1: 'Housing and Home Support',
                listText2: 'Find jobs',
                listText3: 'Buy and sell products through app',
                listText4: 'Post ads for your requirements',
                listText5: 'Filter your options according to your search, location, and price',
                metaTitle: 'Freshy Helpline - Case Studies | GeekyBones',
                metaDescription: 'Freshy Helpline supports newcomers with basic requirements. GeekyBones assisted the client with an online website and app to bring ideas into reality.',
            },
        },
        {
            "name": "candy-coin",
            "data": {
                projectTitle: `Satisfy your Sweet Tooth Cravings!`,
                projectImage: ASSETS.APPDETAILS.CandyCoinProject,
                projectDescription: `Candy Coin brings you deliciously tangy, eye-popping Sour Belts bags. Not only this, while enjoying your juicy flavors, you can also win a free Cryptocurrency. 
Explore the awesome flavors and products.`,
                technology: [
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.NextJs,
                    ASSETS.APPDETAILS.GraphQl,
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ReactImg,
                ],
                resultDescription: "The client wanted an online presence through the website so that customers can have plenty of sweetness. The platform offers versatility, bundled hosting and security, user-friendly software, and built-in features to facilitate transactions, creating an excellent shopping experience. With the right mix of technologies and innovative ideas, GeekyBones helped in fulfilling clients’ objectives.",
                resultSlideList: [
                    ASSETS.APPDETAILS.CandyCoin1,
                    ASSETS.APPDETAILS.CandyCoin2,
                    ASSETS.APPDETAILS.CandyCoin3,
                    ASSETS.APPDETAILS.CandyCoin1,
                    ASSETS.APPDETAILS.CandyCoin2,
                    ASSETS.APPDETAILS.CandyCoin3,
                ],
                listText1: 'Custom Blockchain Integration: We integrated a robust blockchain solution that powers CandyCoin’s secure and transparent transactions. This integration ensures users can buy, sell, and trade with confidence, knowing their assets are protected by state-of-the-art technology.',
                listText2: 'Add to cartUser-Centric Design: Our team crafted a sleek, modern interface that simplifies complex cryptocurrency operations. Whether users are checking their balances, transferring funds, or exploring the market, the platform offers a seamless and intuitive experience across all devices.',
                listText3: 'Advanced Security Protocols: Security was a top priority in the development of CandyCoin. We implemented multi-layered encryption, two-factor authentication, and regular security audits to protect user data and prevent unauthorized access.',
                listText4: 'Payment options - Credit Card, PayPal, and Check/PO',
                listText5: 'Redeem your code',
                listText6: 'Get exclusive offers',
                listText7: 'Join as a brand influencer',
                listText8: 'Join as wholesale distributors',
                metaTitle: 'Candy Coin - Web Development Case Studies | GeekyBones',
                metaDescription: 'Candy Coin offers juicy flavors for cravings. GeekyBones created an online platform fulfilling clients’ objectives, offering consumers with candies. ',
            },
        },
        {
            "name": "quality-minds",
            "data": {
                projectTitle: `Improve the Mental Well-Being and Live a Better Life!`,
                projectImage: ASSETS.APPDETAILS.QualityMindBanner,
                projectDescription: `Quality Mind is a proven program helping people to improve their lives by reducing mental pressure. A personal Mind Mentor provides support by creating a personal development plan to overcome anxiety and depression.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to design a unique personal development program filled with balance, empowerment, and self-love, keeping the mind from self-destructive thoughts. Our team successfully fulfilled the client’s vision while developing robust app solutions. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.APPDETAILS.QualityApp1,
                    ASSETS.APPDETAILS.QualityApp2,
                    ASSETS.APPDETAILS.QualityApp3,
                    ASSETS.APPDETAILS.QualityApp4,
                ],
                listText1: 'Step by step information as your proceed',
                listText2: 'Real-time chat with Mind Mentor™',
                listText3: 'Written or audio journaling',
                listText4: 'Global leader board to track progress',
                listText5: 'Thought Shopping',
                listText6: 'Meditation',
                listText7: 'Bubble Popping',
                metaTitle: 'Quality Mind - Mobile App Development Case Studies | GeekyBones',
                metaDescription: "Quality Minds is a mobile app that helps in improving mental well-being for a better life. GeekyBones fulfilled the client's vision by developing robust application solutions.",
            },
        },
        {
            "name": "tandem",
            "data": {
                projectTitle: ``,
                projectImage: ASSETS.PORTFOLIO.Tandom,
                projectDescription: `Tandem is a language learning app designed to connect users with native speakers for language exchange, helping them improve their speaking skills through real-time conversations. With a focus on fostering communication and cultural exchange, Tandem enables users to practice new languages in an authentic and immersive environment. Our team collaborated with Tandem to enhance its platform with new features, improve user experience, and ensure a seamless, interactive learning journey for language learners worldwide.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to design a unique personal development program filled with balance, empowerment, and self-love, keeping the mind from self-destructive thoughts. Our team successfully fulfilled the client’s vision while developing robust app solutions. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.PORTFOLIO.Tandom,
                    ASSETS.PORTFOLIO.Tandom,
                    ASSETS.PORTFOLIO.Tandom,
                    ASSETS.PORTFOLIO.Tandom,
                ],
                listText1: 'Extensive Story Library:A curated collection of age-appropriate bedtime stories designed to stimulate imagination and language development.Categories and filters for selecting stories based on themes, age groups, or developmental goals.',
                listText2: 'Personalized Recommendations:Implemented AI-driven algorithms to provide story recommendations based on the child’s age, interests, and previous interactions.',
                listText3: 'Interactive Storytelling Features:Audio narration with soothing voiceovers to create an immersive bedtime experience.Options for parents to record their own narration, fostering a deeper connection between parent and child.Visual aids, including animations and illustrations, to enhance comprehension and engagement.',
                listText4: 'Parenting Resources: Integrated tips and guides for parents on the importance of storytelling in early childhood development.Expert advice on leveraging stories to address developmental challenges and milestones.',
                metaTitle: 'Tandom - Mobile App Development Case Studies | GeekyBones',
                metaDescription: "Tandem is a language learning app designed to connect users with native speakers for language exchange, helping them improve their speaking skills through real-time conversations. With a focus on fostering communication and cultural exchange, Tandem enables users to practice new languages in an authentic and immersive environment. Our team collaborated with Tandem to enhance its platform with new features, improve user experience, and ensure a seamless, interactive learning journey for language learners worldwide.",
            },
        },
        {
            "name": "troom",
            "data": {
                projectTitle: `Troom`,
                projectImage: ASSETS.PORTFOLIO.Troom,
                projectDescription: `The Troom App is a sophisticated private driver booking platform designed specifically for residents and travelers in Belgium. Catering to the needs of individuals seeking reliable, convenient, and professional transportation services, Troom provides a seamless way to book private drivers for various occasions. Our team collaborated with Troom to develop a user-friendly, feature-rich mobile and web application that ensures a hassle-free booking experience for users.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to design a unique personal development program filled with balance, empowerment, and self-love, keeping the mind from self-destructive thoughts. Our team successfully fulfilled the client’s vision while developing robust app solutions. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.PORTFOLIO.Troom,
                    ASSETS.PORTFOLIO.Troom,
                    ASSETS.PORTFOLIO.Troom,
                    ASSETS.PORTFOLIO.Troom,
                ],
                listText1: 'Effortless Booking System:Simple and intuitive interface for booking private drivers with just a few taps.Users can select ride preferences such as vehicle type, service duration, and pick-up/drop-off locations.',
                listText2: 'Flexible Booking Options:Support for one-way, round-trip, or hourly bookings tailored to user needs.Option to schedule rides in advance for events, airport transfers, or daily commutes.',
                listText3: 'Premium Driver Network:Verified and professional drivers ensuring safety, reliability, and excellent service quality.User reviews and ratings system to maintain high standards of service.',
                listText4: 'Transparent Pricing:Fare estimation tool to calculate trip costs based on distance, duration, and selected vehicle type.Transparent pricing policies with no hidden fees.',
                metaTitle: 'Troom - Mobile App Development Case Studies | GeekyBones',
                metaDescription: "The Troom App is a sophisticated private driver booking platform designed specifically for residents and travelers in Belgium. Catering to the needs of individuals seeking reliable, convenient, and professional transportation services, Troom provides a seamless way to book private drivers for various occasions. Our team collaborated with Troom to develop a user-friendly, feature-rich mobile and web application that ensures a hassle-free booking experience for users.",
            },
        },
        
        {
            name: "we-are-one",
            data: {
                projectTitle: `We Are One`,
                projectImage: ASSETS.PORTFOLIO.WeAreOne,
                projectDescription: `World of We Are One is an immersive mobile app designed to inspire global unity, mindfulness, and emotional well-being. By focusing on positive thinking, personal growth, and connection, the app provides a platform where users can engage in a variety of activities aimed at fostering a sense of collective consciousness and global harmony. Our team collaborated with We Are One to design and develop a beautifully crafted, user-friendly mobile app that delivers engaging content and encourages users to participate in daily practices for mental, emotional, and spiritual well-being.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to design a unique personal development program filled with balance, empowerment, and self-love, keeping the mind from self-destructive thoughts. Our team successfully fulfilled the client’s vision while developing robust app solutions. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.PORTFOLIO.WeAreOne,
                    ASSETS.PORTFOLIO.WeAreOne,
                    ASSETS.PORTFOLIO.WeAreOne,
                    ASSETS.PORTFOLIO.WeAreOne,
                ],
                listText1: 'Guided Meditation and Mindfulness Practices: We integrated a library of guided meditation sessions and mindfulness exercises to help users relax, center themselves, and reduce stress. The app’s audio and video content is designed to help users cultivate inner peace and emotional balance.',
                listText2: 'Personalized Daily Affirmations: A unique feature of the app is the daily affirmations tool. It delivers personalized positive affirmations to users, encouraging them to start their day with a mindful and empowering mindset. This helps users build resilience, positivity, and gratitude on a daily basis.',
                listText3: 'Interactive Community Forum: The app includes a vibrant and supportive community forum where users can connect with like-minded individuals from around the world. They can share their experiences, offer support, and participate in discussions on topics related to personal growth and collective well-being.',
                listText4: 'Daily Challenges and Growth Activities: We developed a series of daily challenges and activities that encourage users to engage with the app on a consistent basis. These challenges promote self-care, positivity, and emotional awareness, helping users make mindfulness practices a part of their daily routine.',
                metaTitle: 'We Are One - Mobile App Development Case Studies | GeekyBones',
                metaDescription: "World of We Are One is an immersive mobile app designed to inspire global unity, mindfulness, and emotional well-being. By focusing on positive thinking, personal growth, and connection, the app provides a platform where users can engage in a variety of activities aimed at fostering a sense of collective consciousness and global harmony. Our team collaborated with We Are One to design and develop a beautifully crafted, user-friendly mobile app that delivers engaging content and encourages users to participate in daily practices for mental, emotional, and spiritual well-being.",
            },
        },
        {
            name: "swaaad",
            data: {
                projectTitle: `Swaaad`,
                projectImage: ASSETS.PORTFOLIO.Swaaaad,
                projectDescription: `The Swaaad App is a dynamic platform that bridges the gap between food enthusiasts and exceptional culinary experiences. Designed to cater to both food lovers and home kitchens, Swaaad offers a comprehensive solution for discovering, ordering, and enjoying the best nearby food. The app also empowers home kitchens to showcase their unique offerings, including exotic and exclusive dishes, complete with detailed ingredient lists. Our team partnered with Swaaad to create a seamless, user-friendly application suite comprising the main Swaaad App for food lovers and a dedicated Kitchen App for home-based chefs.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to design a unique personal development program filled with balance, empowerment, and self-love, keeping the mind from self-destructive thoughts. Our team successfully fulfilled the client’s vision while developing robust app solutions. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.PORTFOLIO.Swaaaad,
                    ASSETS.PORTFOLIO.Swaaaad,
                    ASSETS.PORTFOLIO.Swaaaad,
                    ASSETS.PORTFOLIO.Swaaaad,
                ],
                listText1: 'Discover Nearby Food:Advanced geolocation features to help users find the best food options nearby.Personalized recommendations based on user preferences, order history, and trending cuisines.',
                listText2: 'Exotic and Exclusive Dishes:A dedicated section highlighting rare and unique dishes crafted by home kitchens.Detailed ingredient breakdowns and chef notes for each dish, offering a transparent and informative experience.',
                listText3: 'Seamless Food Ordering:Easy-to-use ordering system with customizable options for dishes.Real-time order tracking to keep users updated on their delivery status.',
                listText4: 'Home Kitchen Empowerment:Dedicated Kitchen App for home-based chefs to register, manage their menu, and track orders.Tools to showcase exclusive dishes, set pricing, and highlight unique culinary styles.',
                metaTitle: 'Swaaad - Mobile App Development Case Studies | GeekyBones',
                metaDescription: "The Swaaad App is a dynamic platform that bridges the gap between food enthusiasts and exceptional culinary experiences. Designed to cater to both food lovers and home kitchens, Swaaad offers a comprehensive solution for discovering, ordering, and enjoying the best nearby food. The app also empowers home kitchens to showcase their unique offerings, including exotic and exclusive dishes, complete with detailed ingredient lists. Our team partnered with Swaaad to create a seamless, user-friendly application suite comprising the main Swaaad App for food lovers and a dedicated Kitchen App for home-based chefs.",
            },
            },
        {
            "name": "rx-tro",
            "data": {
                projectTitle: `Accomplish Tremendous Productivity Gains With Organised Appointments`,
                projectImage: ASSETS.APPDETAILS.RxTroBanner,
                projectDescription: `RxTro is a centralized industry platform for medical representatives in Australia. It helps organize daily visit logs, manage doctor details, and track other such records, which ultimately improves the productivity of medical representatives.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to create a mobile application platform to help sales representatives in pharmaceutical industries improve their productivity with proper management. Team GeekyBones delivered the work surpassing the client’s expectations. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.APPDETAILS.RxTroMobile1,
                    ASSETS.APPDETAILS.RxTroMobile2,
                    ASSETS.APPDETAILS.RxTroMobile3,
                    ASSETS.APPDETAILS.RxTroMobile4,
                ],
                listText1: 'Manage Appointments',
                listText2: 'Stay updated with notifications',
                listText3: 'Organize daily logs',
                listText4: 'Get and complete Practice’s Request',
                metaTitle: 'RxTro - Mobile App Development Case Studies | GeekyBones',
                metaDescription: 'GeekyBones created the RxTro app to help medical representatives in Australia. It improves productivity by keeping track of daily visits, appointments, etc.',
            },
        },
        {
            "name": "freshy-helpline-mobile",
            "data": {
                projectTitle: `We Help you Make Easy Adjustments to Your New Life`,
                projectImage: ASSETS.APPDETAILS.FreshyBanner,
                projectDescription: `Moving to a new place can be stressful where you need accommodation, jobs, vehicles, etc. Freshy Helpline in Melbourne supports newcomers, especially International students from various communities with basic needs.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to build an online website and mobile app to help people from different communities in Melbourne through ads. The experts at GeekyBones mixed the creative ideas and right tech approach to fulfill client ideas successfully.",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                ASSETS.APPDETAILS.FreshySlider1,
                ASSETS.APPDETAILS. FreshySlider2,
                ASSETS.APPDETAILS. FreshySlider3,
                ASSETS.APPDETAILS. FreshySlider4,
                ],
                listText1: 'Housing and Home Support',
                listText2: 'Find jobs',
                listText3: 'Buy and sell products through app',
                listText4: 'Post ads for your requirements',
                listText5: 'Filter your options according to your search, location, and price',
                metaTitle: 'Freshy Helpline - Case Studies | GeekyBones',
                metaDescription: 'Freshy Helpline supports newcomers with basic requirements. GeekyBones assisted the client with an online website and app to bring ideas into reality.',
            },
        },
        
        {
            "name": "meeting-managment",
            "data": {
                projectTitle: `Manage your Meeting Effectively and Achieve the Desired Results`,
                // projectImage: ASSETS.APPDETAILS.MeetingManagmentBanner,
                projectDescription: `Meetings are opportunities for discussions and collaborations. The 360 Meeting Management app helps in building great meeting habits. The platform allows you to attend the meetings effectively, be accountable for agenda, real-time note-taking, and much more.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client wanted to create a meeting management platform, ensuring that meetings are focused and fruitful. Our team accomplished the client’s expectations by designing an easy and intuitive platform for better meetings. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.APPDETAILS.MeetingManagmentSlider,
                    ASSETS.APPDETAILS.MeetingManagmentSlider2,
                    ASSETS.APPDETAILS.MeetingManagmentSlider3,
                    ASSETS.APPDETAILS.MeetingManagmentSlider4,
                ],
                listText1: 'Create group meetings',
                listText2: 'Automatic notifications of the upcoming meeting',
                listText3: 'Agenda item lead',
                listText4: 'Agenda item priority',
                listText5: 'Add notes, and upload files in Meeting Agenda Item Creation',
                metaTitle: '360 Meeting Management - Case Studies | GeekyBones',
                metaDescription: 'The 360 Meeting Management app helps in managing the meetings. GeekyBones created this intuitive and easy platform for focused and fruitful discussions.',
            },
        },
        {
            "name": "vageto",
            "data": {
                projectTitle: `Food Market at your Convenience!`,
                projectImage: ASSETS.APPDETAILS.VegatoBanner,
                projectDescription: `Vegato App offers the luxury of discovering fresh and quality produce that is delivered at the doorstep. In addition, the platform allows customers to get a hassle-free online grocery on fingertips at affordable prices.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client came with a mission of delivering fresh fruits and vegetables to customers at their doorstep so that they don’t have to move around in crowded local markets, bargaining for quality groceries. Our team developed a robust fresh food platform, helping the client to fulfill the mission successfully. ",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                ASSETS.APPDETAILS.VagetoMobile1,
                ASSETS.APPDETAILS.VagetoMobile2,
                ASSETS.APPDETAILS.VagetoMobile3,
                ASSETS.APPDETAILS.VagetoMobile1,
                ASSETS.APPDETAILS.VagetoMobile2,
                ASSETS.APPDETAILS.VagetoMobile3,
                ],
                listText1: 'Superior and fresh items',
                listText2: 'Customer-friendly user interface',
                listText3: 'Low prices and amazing offers',
                listText4: 'Express delivery service-old',
                listText5: 'Search and order process',
                listText6: 'Secure payment options',
                listText7: 'On-time service-old',
                metaTitle: 'Vegato - Mobile App Development Case Studies | GeekyBones',
                metaDescription: 'Vegato App brings food market at your convenience. GeekyBones build a robust fresh food platform to deliver high-quality products at the doorstep.',
            },
        },
        {
            "name": "sideffect-alert",
            "data": {
                projectTitle: `Stay Updated with Lifesaving Alerts`,
                // projectImage: ASSETS.APPDETAILS.SideffectBanner,
                projectDescription: `Sideeffect Alert app is based on the concept of harm minimization. The alert and awareness system offers the subscribers real-time data on dangerous chemicals and lethal synthetic drugs that are sold nearby.`,
                technology: [
                    ASSETS.APPDETAILS.PostreSql,
                    ASSETS.APPDETAILS.ExpressJs,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.RestApi,
                ],
                resultDescription: "The client had a vision of creating an app for the security of the people where they can keep themselves updated by receiving the notifications directly on their mobile phones. Our experts utilized the right tech support mixed with creative ideas delivering successful results.",
                className: 'common-main-dev-mobile',
                resultSlideList: [
                    ASSETS.APPDETAILS.SideffectMobile1,
                    ASSETS.APPDETAILS.SideffectMobile2,
                    ASSETS.APPDETAILS.SideffectMobile3,
                    ASSETS.APPDETAILS.SideffectMobile1,
                    ASSETS.APPDETAILS.SideffectMobile2,
                    ASSETS.APPDETAILS.SideffectMobile3,
                ],
                listText1: 'Drug alerts',
                listText2: 'Instant Notifications',
                listText3: 'Real-time data',
                metaTitle: 'Sideeffect - Mobile App Development Case Studies | GeekyBones ',
                metaDescription: 'GeekyBones utilised the right tech support and ideas to create a Sideeffect alert app based on the concept of harm minimization.',
            },
        },
        {
            "name": "body-drench",
            "data": {
                projectTitle: `Beauty and Skincare products,`,
                projectImage: ASSETS.PORTFOLIO.BodyDrench,
                projectDescription: `Body Drench is a leading brand in skincare and tanning solutions, offering a wide range of high-quality products to help users achieve healthy, glowing skin. Our development team was entrusted with revamping the Body Drench website to create a visually appealing, functional, and user-friendly platform that reflects the brand’s commitment to excellence.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.BodyDrenchWebsite, ASSETS.APPDETAILS.BodyDrenchWebsite2,ASSETS.APPDETAILS.BodyDrenchWebsite3],
                listText1: 'Elegant and Modern Design: We designed a visually appealing, clean, and modern layout that reflects the elegance of Body Drench. The website features high-quality imagery and a seamless browsing experience, which effectively highlights the luxurious nature of the products.',
                listText2: 'E-commerce Integration: A robust, easy-to-navigate e-commerce platform was built into the website, allowing customers to browse, select, and purchase products with ease. We integrated secure payment gateways for a smooth, safe transaction experience.',
                listText3: 'Comprehensive Product Pages: The website includes detailed product pages with descriptions, ingredient lists, usage instructions, and customer reviews. These pages provide customers with all the information they need to make confident purchasing decisions.',
                listText4: 'Personalized Shopping Experience: We incorporated a personalized shopping feature, allowing customers to create profiles, save favorite products, and receive tailored product recommendations based on their preferences and browsing history.',
                listText5: 'Skincare Tips and Blog Section: To engage users and promote Body Drenchs expertise, we integrated a blog section filled with skincare tips, tanning tutorials, and advice for optimal product usage. This content helps establish the brand as a trusted authority in the beauty industry.',
                listText6: 'Responsive and Mobile-Friendly Design: Understanding the increasing use of mobile devices, the website was designed to be fully responsive, providing an optimal experience across desktop, tablet, and smartphone devices.',
                metaTitle: 'Body Drench | GeekyBones',
                metaDescription: "Body Drench is a leading brand in skincare and tanning solutions, offering a wide range of high-quality products to help users achieve healthy, glowing skin. Our development team was entrusted with revamping the Body Drench website to create a visually appealing, functional, and user-friendly platform that reflects the brand’s commitment to excellence.",
            },
        },
        {
            "name": "cofax",
            "data": {
                projectTitle: `Cofax Business Systems`,
                projectImage: ASSETS.PORTFOLIO.Cofax,
                projectDescription: `Cofax Business Systems is a premier provider of IT solutions and office equipment rentals, empowering Canadian businesses with flexible, reliable, and cost-effective technology options. Our development team collaborated with Cofax to create a robust online platform that highlights their unique offerings, including IT equipment rentals and comprehensive support services.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.CofaxWebsite, ASSETS.APPDETAILS.CofaxWebsite2,ASSETS.APPDETAILS.CofaxWebsite3],
                listText1: 'Online Ticket Submission System: To streamline customer support, we implemented an online ticket submission system that allows users to report issues directly from the website. This feature tracks tickets from submission to resolution, ensuring timely and effective service.',
                listText2: 'Client Portal and Dashboard: A secure client portal was designed to give customers easy access to their rental agreements, service tickets, and billing details. The dashboard provides a centralized location for clients to manage their accounts and interactions with Cofax.',
                listText3: 'Responsive and Mobile-Friendly Design: The website was optimized to be fully responsive, providing a seamless user experience on all devices. Whether accessed on a desktop, tablet, or smartphone, the site maintains its functionality and aesthetic appeal.',
                listText4: 'Clear Navigation and Service Categories: We ensured that the website has intuitive navigation, making it easy for users to find the services they need. Key service areas such as IT equipment rentals, support, and business solutions are clearly categorized for quick access.',
                listText5: 'SEO and Digital Marketing Integration: To improve visibility and attract potential clients, the website was developed with SEO best practices in mind. We integrated analytics and digital marketing tools to enhance lead generation, track performance, and improve conversion rates.',
                listText6: 'Security and Compliance: Given the sensitive nature of business IT solutions, we ensured that the website adheres to industry security standards. We implemented SSL encryption, secure payment processing, and GDPR-compliant data handling to safeguard client information.',
                metaTitle: 'cofax | GeekyBones',
                metaDescription: "Cofax Business Systems is a premier provider of IT solutions and office equipment rentals, empowering Canadian businesses with flexible, reliable, and cost-effective technology options. Our development team collaborated with Cofax to create a robust online platform that highlights their unique offerings, including IT equipment rentals and comprehensive support services.",
            },
        },
        {
            "name": "riveredge",
            "data": {
                projectTitle: `River Edge Advisors`,
                projectImage: ASSETS.PORTFOLIO.RiverEdge,
                projectDescription: `River Edge Advisors is a leading financial consulting firm that specializes in providing tailored advisory services for high-net-worth individuals, families, and businesses. Our development team worked closely with River Edge Advisors to build a sophisticated and user-friendly website that reflects their professional expertise while offering a seamless digital experience for their clients.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.RiverEdgeWebsite, ASSETS.APPDETAILS.RiverEdgeWebsite2,ASSETS.APPDETAILS.RiverEdgeWebsite3],
                listText1: 'Professional, Modern Design: The website was designed with a clean, contemporary aesthetic that aligns with RiverEdge Advisors’ brand identity. The layout is intuitive, making it easy for users to navigate through services, resources, and company information while maintaining a professional and polished appearance.',
                listText2: 'Service Pages for Wealth Management and Retirement Planning: We created detailed, easy-to-navigate service pages that clearly define RiverEdge Advisors’ core offerings, including wealth management, retirement planning, and customized investment strategies. These pages are designed to engage potential clients and provide the information they need to make informed decisions.',
                listText3: 'Client Success Stories and Testimonials: To build trust and credibility, we integrated client testimonials and success stories that highlight the firm’s expertise and positive outcomes. These real-world examples help prospective clients connect with the services offered and understand the value RiverEdge Advisors brings.',
                listText4: 'Resource Hub and Blog Section: A robust resource hub was created, offering visitors educational content such as financial tips, market insights, and retirement planning strategies. This content positions RiverEdge Advisors as a trusted thought leader in the financial consulting space.',
                listText5: 'Interactive Financial Tools and Calculators: To enhance user experience and engagement, we incorporated interactive financial tools and calculators that allow users to assess their financial goals, investment plans, and retirement preparedness. These tools provide immediate value and encourage further interaction with the site.',
                listText6: 'Responsive, Mobile-Friendly Design: The website is fully responsive, ensuring that clients and visitors have a seamless experience across all devices—whether on a desktop, tablet, or smartphone. This mobile-friendly design ensures easy access for clients on the go.',
                metaTitle: 'River Edge | GeekyBones',
                metaDescription: "River Edge Advisors is a leading financial consulting firm that specializes in providing tailored advisory services for high-net-worth individuals, families, and businesses. Our development team worked closely with River Edge Advisors to build a sophisticated and user-friendly website that reflects their professional expertise while offering a seamless digital experience for their clients.",
            },
        },

        {
            "name": "frontfooters",
            "data": {
                projectTitle: `FrontFooters`,
                projectImage: ASSETS.PORTFOLIO.FrontFooters,
                projectDescription: `Frontfooters is a dynamic agency that specializes in providing cutting-edge marketing solutions, strategy consulting, and digital transformation services to businesses across various industries. Our team worked closely with Frontfooters to develop a robust, visually engaging, and user-friendly website that effectively conveys their services and connects them with potential clients.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.FrontFootersWebsite, ASSETS.APPDETAILS.FrontFootersWebsite2,ASSETS.APPDETAILS.FrontFootersWebsite3],
                listText1: 'Service Offerings Pages: We created distinct service pages detailing Front Footers’ core offerings, including branding, digital marketing, web design, and content creation. Each service page is designed to highlight the agencys expertise and showcase their customized solutions for clients.',
                listText2: 'Portfolio and Case Studies: The website includes a comprehensive portfolio section, where potential clients can explore previous projects and case studies. These real-world examples showcase Front Footers’ creative solutions, detailing challenges, approaches, and results, and helping to build trust with prospective clients.',
                listText3: 'Interactive Contact Forms: To encourage inquiries and foster engagement, we integrated customizable, user-friendly contact forms. These forms allow visitors to request consultations, ask questions, and get in touch with the team in a streamlined way.',
                listText4: 'Responsive and Mobile-Optimized Design: The website is fully responsive, ensuring that users on any device—whether desktop, tablet, or smartphone—experience the same seamless, high-quality browsing experience. This mobile optimization ensures accessibility for all users.',
                listText5: 'Social Media Integration: The website includes social media feeds and integration, allowing users to easily follow Front Footers on platforms like Instagram, LinkedIn, and Twitter. This social integration helps build the agency’s online presence and connects visitors with the brand’s latest updates and content.',
                listText6: 'Blog and Resource Center: We added a blog section to position Front Footers as a thought leader in the marketing space. The blog features articles on the latest marketing strategies, industry trends, and practical advice for businesses looking to grow their brands.',
                metaTitle: 'Front Footers | GeekyBones',
                metaDescription: "Frontfooters is a dynamic agency that specializes in providing cutting-edge marketing solutions, strategy consulting, and digital transformation services to businesses across various industries. Our team worked closely with Frontfooters to develop a robust, visually engaging, and user-friendly website that effectively conveys their services and connects them with potential clients.",
            },
        },

        {
            "name": "el-rancho-vista",
            "data": {
                projectTitle: `El Rancho Vista`,
                projectImage: ASSETS.PORTFOLIO.ElRanchoVista,
                projectDescription: `El Rancho Vista Care is likely a healthcare or senior living facility offering care services. They may focus on providing support for elderly residents, such as assisted living, memory care, or rehabilitation services.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.ElRanchoVistaWebsite, ASSETS.APPDETAILS.ElRanchoVistaWebsite2,ASSETS.APPDETAILS.ElRanchoVistaWebsite3],
                listText1: 'Warm and Inviting Design: The website was designed with a warm, welcoming aesthetic to reflect the comforting environment El Rancho Vista Care offers. The design incorporates soft colors, inviting imagery, and user-friendly navigation, creating a sense of security and trust for potential residents and their families.',
                listText2: 'Detailed Service Pages: We developed service pages that comprehensively outline the care options offered, including assisted living, memory care, and rehabilitation services. These pages provide clear, accessible information about each service, helping families make informed decisions for their loved ones.',
                listText3: 'Virtual Tour and Facility Gallery: Understanding the importance of visual appeal when choosing a care facility, we integrated a virtual tour feature and a photo gallery showcasing the facility’s rooms, amenities, and common areas. This feature gives visitors a realistic and reassuring look at the environment, making them feel more connected to the space before visiting in person.',
                listText4: 'Resident and Family Testimonials: To build trust and credibility, the website includes testimonials from current and past residents and their families. These stories emphasize the quality of care and the positive impact El Rancho Vista Care has had on the lives of its residents.',
                listText5: 'Contact and Inquiry Forms: The website includes easy-to-use contact forms for inquiries, allowing potential residents or their families to request more information, schedule tours, or ask questions directly from the site. The form ensures that all inquiries are processed in a timely and organized manner.',
                listText6: 'Staff Introduction and Team Bios: To establish a personal connection, we included a section where visitors can learn about the compassionate team at El Rancho Vista Care, including staff bios, qualifications, and their commitment to resident care. This helps foster a sense of transparency and trust.',
                metaTitle: 'El Rancho Vista | GeekyBones',
                metaDescription: "El Rancho Vista Care is likely a healthcare or senior living facility offering care services. They may focus on providing support for elderly residents, such as assisted living, memory care, or rehabilitation services.",
            },
        },

        {
            "name": "yard-sign-plus",
            "data": {
                projectTitle: `Yard Sign Plus`,
                projectImage: ASSETS.PORTFOLIO.YSP,
                projectDescription: `Yard Sign Plus is a leading provider of custom yard signs and printing solutions, catering to individuals, businesses, and organizations seeking high-quality signage for various needs. Our development team worked with Yard Sign Plus to create a visually striking, user-friendly, and highly functional website that effectively showcases their diverse product offerings while streamlining the ordering process for customers.`,
                technology: [
                    ASSETS.APPDETAILS.FabricJs,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.MySql,
                    ASSETS.APPDETAILS.SymfonyImg,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.YspWebsite, ASSETS.APPDETAILS.YspWebsite2,ASSETS.APPDETAILS.YspWebsite3],
                listText1: 'E-commerce Platform for Custom Sign Orders: The website features an integrated e-commerce platform that allows customers to easily browse, customize, and order yard signs directly online. The intuitive product customization tool enables users to upload logos, add text, and choose from various sign sizes and colors.',
                listText2: 'Product Catalog with Detailed Descriptions: We built an organized product catalog that highlights the different types of yard signs available, such as real estate signs, event signs, and business signage. Each product page includes detailed descriptions, material options, pricing, and high-quality images to guide customers in their decision-making process.',
                listText3: 'Customizable Online Design Tool: To enhance the user experience, we implemented a customizable design tool that lets customers design their yard signs in real-time. Users can easily adjust text, colors, and graphics, ensuring their signs match their exact vision before placing an order.',
                listText4: 'Mobile-Optimized Design: Understanding the importance of accessibility, we made sure the website is fully responsive, allowing customers to seamlessly browse and place orders from mobile devices, tablets, and desktops. This ensures a consistent experience across all platforms.',
                listText5: 'Easy Checkout and Secure Payment Options: The site includes a streamlined checkout process with multiple payment options, including credit cards and PayPal, ensuring that customers can quickly and securely complete their orders.',
                listText6: 'Order Tracking and Notifications: We integrated an order tracking system that allows customers to track the status of their sign orders from production to delivery. Automated email notifications keep customers informed about their order status, enhancing their experience and satisfaction.',
                metaTitle: 'Yard Sign Plus | GeekyBones',
                metaDescription: "Yard Sign Plus is a leading provider of custom yard signs and printing solutions, catering to individuals, businesses, and organizations seeking high-quality signage for various needs. Our development team worked with Yard Sign Plus to create a visually striking, user-friendly, and highly functional website that effectively showcases their diverse product offerings while streamlining the ordering process for customers.",
            },
        },

        {
            "name": "lingo-tech-ai",
            "data": {
                projectTitle: `Lingo Teach AI`,
                projectImage: ASSETS.PORTFOLIO.LingoTechAi,
                projectDescription: `LingoTeach.AI is an innovative language learning platform that leverages artificial intelligence to provide personalized and immersive language education. Our development team collaborated with LingoTeach.AI to create a cutting-edge website that reflects the brand's advanced technology and enhances the learning experience for users.`,
                technology: [
                    ASSETS.APPDETAILS.FabricJs,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.ReactImg,
                    ASSETS.APPDETAILS.MySql,
                    ASSETS.APPDETAILS.SymfonyImg,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.LingoTechAIWebsite, ASSETS.APPDETAILS.LingoTechAIWebsite2,ASSETS.APPDETAILS.LingoTechAIWebsite2],
                listText1: 'AI-Powered Language Learning: At the heart of LingoTeach.ai is its AI-powered language learning system, which adapts lessons based on the user’s proficiency level, learning speed, and preferences. We developed an intuitive interface that seamlessly guides users through their personalized learning paths.',
                listText2: 'Interactive Lessons and Gamification: The website integrates interactive lessons, quizzes, and challenges that help users learn in an engaging way. Gamification elements, such as points, badges, and leaderboards, were incorporated to motivate users and make language learning fun.',
                listText3: 'Multilingual Support: The platform is designed to support a wide range of languages, allowing users to select their preferred language for learning. This feature ensures that LingoTeach.ai can serve a diverse, global audience.',
                listText4: 'Responsive and Mobile-Friendly Design: Understanding the growing trend of mobile learning, the website was built to be fully responsive. It offers a seamless experience across desktop, tablet, and mobile devices, ensuring users can learn on-the-go from any device.',
                listText5: 'User Profiles and Progress Tracking: We implemented user profiles that track progress, scores, and areas for improvement. This allows users to monitor their learning journey, set goals, and continue where they left off, ensuring an organized and personalized experience.',
                listText6: 'Subscription-Based Model and Payment Integration: The website features a user-friendly subscription model with various payment options, including credit cards and PayPal. Users can easily subscribe to different tiers based on their learning needs, with secure payment gateways integrated for smooth transactions.',
                metaTitle: 'Lingo Teach | GeekyBones',
                metaDescription: "LingoTeach.AI is an innovative language learning platform that leverages artificial intelligence to provide personalized and immersive language education. Our development team collaborated with LingoTeach.AI to create a cutting-edge website that reflects the brand's advanced technology and enhances the learning experience for users.",
            },
        },
        {
            "name": "soullyf",
            "data": {
                projectTitle: `Soullyf`,
                projectImage: ASSETS.PORTFOLIO.Soul,
                projectDescription: `Soullyf is a holistic wellness platform focused on promoting mental, physical, and emotional well-being through curated wellness resources, guidance, and community support. Our development team collaborated with Soullyf to create an intuitive, visually engaging, and feature-rich website that serves as both a resource hub and a community space for individuals seeking to improve their overall health and wellness.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.SoulWebsite, ASSETS.APPDETAILS.SoulWebsite2,ASSETS.APPDETAILS.SoulWebsite3],
                listText1: 'Personalized Wellness Programs: The website was designed to showcase Soullyf’s range of personalized wellness programs. Users can select from various fitness plans, mindfulness exercises, and emotional well-being resources tailored to their specific needs, goals, and preferences.',
                listText2: 'Interactive Mindfulness Tools: We integrated interactive tools that guide users through mindfulness exercises such as meditation, breathing exercises, and journaling prompts. These features encourage users to engage with the platform on a daily basis and promote mental clarity and relaxation.',
                listText3: 'Wellness Resource Library: A comprehensive library was developed, offering articles, videos, and tutorials on topics related to physical fitness, mental health, nutrition, and stress management. This resource section allows users to explore wellness topics and gain actionable insights to improve their lifestyle.',
                listText4: 'Community Engagement Features: Soullyf emphasizes the importance of community in achieving wellness. The website includes a forum and social features where users can share their wellness journeys, connect with others, participate in group challenges, and offer support through discussions.',
                listText5: 'Client Support and Contact Features: The website features easy-to-access contact forms, customer support chat, and a knowledge base to address any questions or concerns users may have. This ensures that all users receive the support they need throughout their wellness journey.',
                listText6: 'SEO Optimization and Content Strategy: The website was built with SEO best practices in mind to help Soullyf rank highly in search results for wellness and mindfulness-related queries. The content strategy includes blog posts and articles that not only engage users but also help the platform attract organic traffic.',
                metaTitle: 'soullyf | GeekyBones',
                metaDescription: "Soullyf is a holistic wellness platform focused on promoting mental, physical, and emotional well-being through curated wellness resources, guidance, and community support. Our development team collaborated with Soullyf to create an intuitive, visually engaging, and feature-rich website that serves as both a resource hub and a community space for individuals seeking to improve their overall health and wellness.",
            },
        },

        {
            "name": "evium-charging",
            "data": {
                projectTitle: `EVIUM CHARGING`,
                projectImage: ASSETS.PORTFOLIO.Evium,
                projectDescription: `Evium Charging is a forward-thinking company providing electric vehicle (EV) charging solutions for businesses, communities, and individual customers. Their goal is to make EV charging more accessible, efficient, and sustainable. Our development team collaborated with Evium Charging to create a modern, functional, and informative website that highlights their innovative products and services while providing a seamless user experience for their diverse customer base.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.EviumWebsite, ASSETS.APPDETAILS.EviumWebsite2,ASSETS.APPDETAILS.EviumWebsite3],
                listText1: 'Charging Station Locator: We developed an interactive and easy-to-use charging station locator, allowing users to find nearby EV charging stations based on their location. This feature integrates a map with real-time data on station availability, making it convenient for users to find a charger when needed.',
                listText2: 'User Registration and Account Management: The website includes a user-friendly registration system, allowing customers to create accounts to track their charging history, manage payment methods, and access exclusive deals and updates. The personalized account dashboard provides users with a streamlined experience.',
                listText3: 'E-commerce Integration for Charging Accessories: The platform includes an online store where users can purchase EV charging accessories such as cables, adapters, and installation kits. This e-commerce section is fully integrated with secure payment options and easy navigation for a smooth shopping experience.',
                listText4: 'Subscription and Payment Plans: We integrated a subscription model that allows customers to choose from various payment plans based on their charging needs. Customers can subscribe to packages that offer discounted rates for frequent use, and the site supports multiple payment options, ensuring a secure and convenient checkout process.',
                listText5: 'Real-Time Charging Station Status: We implemented a real-time status feature for charging stations, allowing users to check the availability and operational status of stations before planning their visit. This reduces the frustration of arriving at a station only to find it unavailable.',
                listText6: 'Responsive and Mobile-Friendly Design: The website was designed to be fully responsive, ensuring an optimized user experience across desktop, tablet, and mobile devices. This makes it easy for users to search for charging stations and manage their accounts on-the-go.',
                metaTitle: 'EVIUM CHARGING - Case Studies | GeekyBones',
                metaDescription: "Evium Charging is a forward-thinking company providing electric vehicle (EV) charging solutions for businesses, communities, and individual customers. Their goal is to make EV charging more accessible, efficient, and sustainable. Our development team collaborated with Evium Charging to create a modern, functional, and informative website that highlights their innovative products and services while providing a seamless user experience for their diverse customer base.",
            },
        },

        {
            "name": "Installims",
            "data": {
                projectTitle: `Installims`,
                projectImage: ASSETS.PORTFOLIO.Installims,
                projectDescription: `InstallIMS is a comprehensive installation management system designed to help businesses efficiently manage their installation processes, from scheduling and tracking to invoicing and reporting. Our development team worked closely with InstallIMS to create a clean, functional, and user-friendly website that showcases the platform’s robust features while providing a seamless experience for users seeking to optimize their installation operations.`,
                technology: [
                    ASSETS.APPDETAILS.Wordpress,
                    ASSETS.APPDETAILS.PhpImg,
                    ASSETS.APPDETAILS.Gutenberg,
                    ASSETS.APPDETAILS.MySql,
                ],
                resultDescription: "Our client wanted a website and apps that could be accessible to both drivers and riders. As we accepted our clients business as our own, we successfully delivered the project by accomplishing clients goals. From designing to development and then implementation, we ensured that our client was fully satisfied. ",
                resultSlideList: [ASSETS.APPDETAILS.InstallimsWebsite, ASSETS.APPDETAILS.InstallimsWebsite,ASSETS.APPDETAILS.InstallimsWebsite],
                listText1: 'Installation Management Dashboard: We developed an intuitive, interactive dashboard that allows businesses to efficiently manage and track their installation projects. The dashboard includes key features such as task assignment, project timelines, progress tracking, and real-time updates, all designed to streamline workflows and improve project efficiency.',
                listText2: 'Service Request and Ticketing System: A key feature of the website is the integrated service request and ticketing system. Users can easily submit service requests, and the system automatically generates tickets, assigns them to appropriate personnel, and tracks their resolution. This system ensures that all requests are handled promptly and efficiently.',
                listText3: 'Vendor Management System: The platform includes a robust vendor management system, allowing businesses to collaborate with third-party service providers and installers. This feature enables seamless communication, invoicing, and performance tracking, ensuring a smooth and efficient installation process.',
                listText4: 'Customizable Reporting and Analytics: The website features advanced reporting tools that enable users to generate customizable reports on installation performance, project timelines, and resource allocation. This data-driven approach helps businesses make informed decisions and optimize their installation operations.',
                listText5: 'Mobile-Friendly Design for On-the-Go Access: Understanding the need for flexibility, we made sure that the website is fully responsive, ensuring an optimized experience on desktop, tablet, and mobile devices. Field service providers and clients can access the platform from anywhere, enabling real-time updates and seamless management.',
                listText6: 'Integration with Third-Party Tools: We integrated InstallIMS with various third-party tools and software that clients may already be using for business operations. This ensures a smooth data flow across different systems and enhances the overall functionality of the platform.',
                metaTitle: 'Installims | GeekyBones',
                metaDescription: "InstallIMS is a comprehensive installation management system designed to help businesses efficiently manage their installation processes, from scheduling and tracking to invoicing and reporting. Our development team worked closely with InstallIMS to create a clean, functional, and user-friendly website that showcases the platform’s robust features while providing a seamless experience for users seeking to optimize their installation operations.",
            },
        },

        
    ];

    const row = data.filter((item) => item.name === name);

    if(row.length === 0){
        return <PageNotFound />;
    }
    return (
        <Layout headerCustomClass={'gb-header-main-wrapper-inner'} breadcrumbView={true} pageTitle={name} currentPage={name} lastRoute={'portfolio'} lastRouteUrl={'/portfolio/web-development'} metaTitle={row[0].data.metaTitle} metaDescription={row[0].data.metaDescription}>
            <Banner data={row[0].data} />
            <AppDetailTechnologySlider data={row[0].data}  />
            <Result data={row[0].data} />
            {name === 'all-in' ?
                <KeyFeatureAllIn/> : <KeyFeature data={row[0].data} />
            }
        </Layout>
    )
}
export default Detail;
