const COMMON = {
    ArrowRight: require("../../../assets/images/arrow-right.png").default,
    ArrowRightDouble: require("../../../assets/images/arrow-right-double.png").default,
    ArrowLeftBlack: require("../../../assets/images/arrow-left-black.png").default,
    ArrowRightBlack: require("../../../assets/images/arrow-right-black.png").default,
    ArrowUpWhite: require("../../../assets/images/arrow-up-white.png").default,
    ArrowDownWhite: require("../../../assets/images/arrow-down-white.png").default,
    ArrowUpRed: require("../../../assets/images/arrow-up-red.png").default,
    Headphones: require("../../../assets/images/headphones.png").default,
    Map: require("../../../assets/images/location.png").default,
    Envelope: require("../../../assets/images/envelope.png").default,
    EnvelopeFilled: require("../../../assets/images/envelope-filled.png").default,
    InstagramWhite: require("../../../assets/images/instagram-white.png").default,
    SkypeWhite: require("../../../assets/images/skype-white.png").default,
    WhatsappWhite: require("../../../assets/images/whatsapp-white.png").default,
    PlusIconWhite: require("../../../assets/images/plus-white-icon.png").default,
    Send: require("../../../assets/images/send.png").default,
    CommonServicesBannerBg: require("../../../assets/images/common-services-banner-bg.webp").default,
    CommonServicesBannerIcon: require("../../../assets/images/common-services-banner-icon.png").default,
    ApproachIcon: require("../../../assets/images/approach-common-icon.png").default,
    DevelopmentIcon: require("../../../assets/images/development-common-icon.png").default,
    IconServices1: require("../../../assets/images/icon-services-1.png").default,
    IconServices2: require("../../../assets/images/icon-services-2.png").default,
    IconServices3: require("../../../assets/images/icon-services-3.png").default,
    IconServices4: require("../../../assets/images/icon-services-4.png").default,
    IconServices5: require("../../../assets/images/icon-services-5.png").default,
    IconServices6: require("../../../assets/images/icon-services-6.png").default,
    IconServices7: require("../../../assets/images/icon-services-7.png").default,
    CalendarWhite: require("../../../assets/images/calendar-white.png").default,
    KeyboardWhite: require("../../../assets/images/keyboard-white.png").default,
    TestWhite: require("../../../assets/images/test-white.png").default,
    SeoWhite: require("../../../assets/images/seo-white.png").default,
    SettingsWhite: require("../../../assets/images/settings-white.png").default,
    AndroidBlack: require("../../../assets/images/android-black.png").default,
    ReactBlack: require("../../../assets/images/react-black.png").default,
    BrochureDesign: require("../../../assets/images/brochure-design.png").default,
    FlyerDesign: require("../../../assets/images/flyer-design.png").default,
    IconDesign: require("../../../assets/images/icon-design.png").default,
    IllustrationDesign: require("../../../assets/images/illustration-design.png").default,
    InfographicDesign: require("../../../assets/images/infographic-design.png").default,
    MobileAppDesign: require("../../../assets/images/mobile-app-design.png").default,
    WebsiteDesign: require("../../../assets/images/website-design.png").default,
    Zoom: require("../../../assets/images/zoom-button-icon.png").default,
    star:require("../../../assets/images/star.png").default,
    like:require("../../../assets/images/love.png").default,
    google:require("../../../assets/images/google.png")
}
const HOME = {
    Logo: require("../../../assets/images/logo.png").default,
    Bar: require("../../../assets/images/bar.png").default,
    LogoWhite: require("../../../assets/images/logo-white.png").default,
    CommonHeaderShape2: require("../../../assets/images/header-common-shape-2.png").default,
    CommonHeaderShape4: require("../../../assets/images/header-common-shape-4.png").default,
    CommonHeaderShape5: require("../../../assets/images/testimonial-shape.png").default,
    CommonHeaderShape12: require("../../../assets/images/temp-shape.png").default,
    HomeBannerIcon: require("../../../assets/images/home-banner-icon.png").default,
    OurExpert: require("../../../assets/images/our-expert.png").default,
    ServiceIcon1: require("../../../assets/images/service-icon1.png").default,
    ServiceIcon2: require("../../../assets/images/service-icon2.png").default,
    ServiceIcon3: require("../../../assets/images/service-icon3.png").default,
    ServiceIcon4: require("../../../assets/images/service-icon4.png").default,
    CircleTick: require("../../../assets/images/circle-red-tick.png").default,
    Portfolio1: require("../../../assets/images/portfolio-1.png").default,
    Portfolio2: require("../../../assets/images/portfolio-2.png").default,
    Portfolio3: require("../../../assets/images/portfolio-3.png").default,
    Portfolio4: require("../../../assets/images/portfolio-4.png").default,
    Portfolio5: require("../../../assets/images/portfolio-5.png").default,
    Portfolio6: require("../../../assets/images/portfolio-6.png").default,
    Portfolio7: require("../../../assets/images/portfolio-7.png").default,
    Portfolio8: require("../../../assets/images/portfolio-8.png").default,
    Blog1: require("../../../assets/images/blog-1.png").default,
    Blog2: require("../../../assets/images/blog-2.png").default,
    FlutterSvg: require("../../../assets/images/flutter-svg.svg").default,
    AndroidLogoHome: require("../../../assets/images/android-logo-home.webp").default,
    SwiftHome: require("../../../assets/images/swift-home.png").default,
    Mobile2Home: require("../../../assets/images/Group 50613.webp").default,
    LaravelHome: require("../../../assets/images/laravel-home.png").default,
    ZendHome: require("../../../assets/images/zend-home.png").default,
    DECO:require("../../../assets/images/Daco_4989583.png").default,
    NESTJS:require("../../../assets/images/nextjs-icon-512x512-y563b8iq.png").default,
    MONGODB:require("../../../assets/images/mongo.png").default,
    AWS:require("../../../assets/images/g1865.png").default,
    CodineitherHome: require("../../../assets/images/codineither-home.png").default,
    CakephpHome: require("../../../assets/images/cakephp-home.png").default,
    WordpressImg: require("../../../assets/images/wordpress-img.webp").default,
    TechSportGear: require("../../../assets/images/sgspro.png").default,
    Auslankamatrimony: require("../../../assets/images/Auslankamatrimony.png").default,
    Mav3rik: require("../../../assets/images/Mav3rik.png").default,
    WordpressHome: require("../../../assets/images/wordpress-home.png").default,
    MagentoHome: require("../../../assets/images/magento-home.webp").default,
    WixHome: require("../../../assets/images/wix-home.png").default,
    ReactHome: require("../../../assets/images/react-home.png").default,
    Logo2: require("../../../assets/images/logo2.jpg").default,
    User: require("../../../assets/images/user.png").default,
    Shopify: require("../../../assets/images/shopify-green.webp").default,
    OpenCart: require("../../../assets/images/opencart.png").default,
    ReactWhiteIcon: require("../../../assets/images/react-white-logo.png").default,
    AngularWhiteIcon: require("../../../assets/images/angularjs-white-logo.png").default,
    LaravelWhiteIcon: require("../../../assets/images/laravel-white-logo.png").default,
    NodeWhiteIcon: require("../../../assets/images/nodejs-white-logo.png").default,
    ShopifyWhiteIcon: require("../../../assets/images/shopify-white-logo.png").default,
    SymfonyWhiteIcon: require("../../../assets/images/symfony-white-logo.png").default,
    JavaWhiteIcon: require("../../../assets/images/java-white-logo.png").default,
    PhpWhiteIcon: require("../../../assets/images/php-white-logo.png").default,
    ReactNativeWhiteIcon: require("../../../assets/images/react-white-logo.png").default,
    WixWhiteIcon: require("../../../assets/images/wix-white-logo.png").default,
    WordpressWhiteIcon: require("../../../assets/images/wordpress-white-logo.png").default,
    FacebookWhiteICon: require("../../../assets/images/facebook-white-icon.png").default,
    InstagramWhiteICon: require("../../../assets/images/instagram-white-icon.png").default,
    LinkedinWhiteICon: require("../../../assets/images/linkedin-whtie-icon.png").default,
    SkypeWhiteICon: require("../../../assets/images/skype-white.png").default,
    FlutterWhiteICon: require("../../../assets/images/flutter-white-icon.png").default,


}
const ABOUT = {                                                                                                                                                                                                         
    HowADayStart: require("../../../assets/images/how-day-start.png").default,                                                                                                                                                          
    GreatCommunication: require("../../../assets/images/great-communication.png").default,
    DaishyGoyal: require("../../../assets/images/daishy-goyal.png").default,
    ManojSaini: require("../../../assets/images/manoj-saini.png").default,
    CircleLeft: require("../../../assets/images/ah-doote-left.jpg").default,
    OurMission: require("../../../assets/images/our-mission.jpg").default,
    About: require("../../../assets/images/About.png").default,
    achievement: require("../../../assets/images/Group 42603.png").default,
    LeaderDaishyGoyal: require("../../../assets/images/leader-daishy-goyal.png").default,
    LeaderPreetiGoyal: require("../../../assets/images/leader-preeti-goyal.png").default,
    LeaderManojKumar: require("../../../assets/images/leader-manoj-kumar.png").default,
    Integrity: require("../../../assets/images/integrity.png").default,
    TimelyDelivery: require("../../../assets/images/timely-delivery.png").default,
    CustomerDelight: require("../../../assets/images/customer-delight.png").default,
    WeQuantifySuccess: require("../../../assets/images/we-quantify-success.png").default,
}
const SERVICES = {
    Java: require("../../../assets/images/java.png").default,
    Swift: require("../../../assets/images/swift.png").default,
    Flutter: require("../../../assets/images/flutter.png").default,
    ReactNative: require("../../../assets/images/react-native.png").default,
    PhoneGap: require("../../../assets/images/phone-gap.png").default,
    Node: require("../../../assets/images/node.png").default,
    Symfony: require("../../../assets/images/node.png").default,
    Laravel: require("../../../assets/images/laravel.png").default,
    WordPress: require("../../../assets/images/wordpress.png").default,
    React: require("../../../assets/images/react-native.png").default,
    MobileServices: require("../../../assets/images/mobile-services.png").default,
    DesktopServices: require("../../../assets/images/desktop-services.png").default,
    HybridMobileApp: require("../../../assets/images/hybrid-app.png").default,
    IosApp: require("../../../assets/images/ios-app.png").default,
    AndroidApp: require("../../../assets/images/android-app.png").default,
    WhatWeIcon1: require("../../../assets/images/what-we-do-icon-1.png").default,
    WhatWeIcon2: require("../../../assets/images/what-we-do-icon-2.png").default,
    WhatWeIcon3: require("../../../assets/images/what-we-do-icon-3.png").default,
    WhatWeIcon4: require("../../../assets/images/what-we-do-icon-4.png").default,
    Accepted: require("../../../assets/images/accepted.png").default,
    AndroidLogo: require("../../../assets/images/android-logo-2.png").default,
    AppleLogo: require("../../../assets/images/apple-logo-2.png").default,
    IonicLogo: require("../../../assets/images/ionic-logo.png").default,
    FlutterLogo: require("../../../assets/images/flutter-logo-3.png").default,
    ReactLogo: require("../../../assets/images/react-logo-with-text.png").default,
    MobileAppService1: require("../../../assets/images/mobile-app-service-1.png").default,
    MobileAppService2: require("../../../assets/images/mobile-app-service-2.png").default,
    MobileAppService3: require("../../../assets/images/mobile-app-service-3.png").default,
    MobileAppService4: require("../../../assets/images/mobile-app-service-4.png").default,
    MobileAppService5: require("../../../assets/images/mobile-app-service-5.png").default,
    MobileAppService6: require("../../../assets/images/mobile-app-service-6.png").default,
    MobileImage1: require("../../../assets/images/mobile-1.jpg").default,
    MobileImage2: require("../../../assets/images/mobile-2.webp").default,
    SliderArrowLeft: require("../../../assets/images/left-arrow.png").default,
    SliderArrowRight: require("../../../assets/images/right-arrow.png").default,
    SliderArrowLeftWhite: require("../../../assets/images/Group 50583.png").default,
    SliderArrowRightWhite: require("../../../assets/images/Group 50578@2x.png").default,
    Check: require("../../../assets/images/check.png").default,
    Graphic1: require("../../../assets/images/graphic-1.webp").default,
    Graphic2: require("../../../assets/images/graphic-2.webp").default,
    Tools: require("../../../assets/images/tools.png").default,
    WebDesignServices: require("../../../assets/images/web-design-services.png").default,
    LaravelServices: require("../../../assets/images/laravel-services.png").default,
    NodejsServices: require("../../../assets/images/node-js-services.png").default,
    WordpressServices: require("../../../assets/images/wordpress-services.png").default,
    SymfonyServices: require("../../../assets/images/symfony-services.png").default,
    WebDevelopmentServices: require("../../../assets/images/web-development-services.png").default,
    MobileAppServices: require("../../../assets/images/mobile-app-services.png").default,
    GraphicDesignServices: require("../../../assets/images/graphic-design-services.png").default,
    DigitalMarketingServices: require("../../../assets/images/digital-marketing-services.png").default,
    CloudBlack: require("../../../assets/images/cloud-black.png").default,
}
const PORTFOLIO = {
    SymfonyBlack: require("../../../assets/images/php-symfony.png").default,
    LaravelLogo: require("../../../assets/images/laravel-logo.png").default,
    CodelgniterLogo: require("../../../assets/images/codelgniter-logo.png").default,
    CakePhpLogo: require("../../../assets/images/cakephp-logo.png").default,
    ReactLogo: require("../../../assets/images/react-logo.png").default,
    ShopifyLogo: require("../../../assets/images/shopify-logo.png").default,
    WordpressLogo: require("../../../assets/images/wordpress-logo.png").default,
    IosAppDevelopmentBanner: require("../../../assets/images/ios-apps.jpg").default,
    ReactTestImage: require("../../../assets/images/react-man-test.jpeg").default,
    SymfonyProject: require("../../../assets/images/symfony-project.jpg").default,
    IosProject: require("../../../assets/images/ios-project.png").default,
    AndroidProject: require("../../../assets/images/android-project.png").default,
    AllInOne:require('../../../assets/images/all-in-one.png').default,
    SportGear:require('../../../assets/images/sport-gear.png').default,
    SportGearDetails:require('../../../assets/images/sport-gear-details.png').default,
    Mavrik:require('../../../assets/images/mavrik.png').default,
    Swaaad:require('../../../assets/images/swaaad.png').default,
    TadPole:require("../../../assets/images/tadpole.png").default,
    Auslankmatrimony:require('../../../assets/images/auslankmatrimony.png').default,
    QualityMindApp:require('../../../assets/images/quality-mind.png').default,
    CandyCoin:require('../../../assets/images/candy-coin.png').default,
    CandyCoinlogo:require('../../../assets/images/CandyCoin.png').default,
    TadpoleRides:require('../../../assets/images/tadpole-app.png').default,
    RxTro:require("../../../assets/images/rxtro.png").default,
    FreshyApp:require("../../../assets/images/freshy-app.png").default,
    TadpoleApp:require("../../../assets/images/tadpole-app.png").default,
    MeetingManagmentApp:require("../../../assets/images/meeting-managment-app.png").default,
    VegatoApp:require("../../../assets/images/vegato-app.png").default,
    SideffectApp:require("../../../assets/images/sideffect-app.png").default,
    GraphicEcommerceDesign:require("../../../assets/images/graphic-ecommerce-design.png").default,
    GraphicDesign1:require("../../../assets/images/graphic-design-1.png").default,
    GraphicDesign2:require("../../../assets/images/graphic-design-2.png").default,
    GraphicDesign3:require("../../../assets/images/graphic-design-3.png").default,
    GraphicDesign4:require("../../../assets/images/graphic-design-4.png").default,
    GraphicDesign5:require("../../../assets/images/graphic-design-5.png").default,
    GraphicDesign6:require("../../../assets/images/graphic-design-6.png").default,
    GraphicDesign7:require("../../../assets/images/graphic-design-7.png").default,
    GraphicDesign8:require("../../../assets/images/graphic-design-8.png").default,
    GraphicDesign9: require("../../../assets/images/graphic-design-9.png").default,
    BodyDrench: require("../../../assets/images/body dranceh.png").default,
    FrontFooters: require("../../../assets/images/frontfooter.png").default,
    RiverEdge: require("../../../assets/images/riveredge.png").default,
    Cofax: require("../../../assets/images/cofax-web.png").default,
    ElRanchoVista: require("../../../assets/images/elrancho.png").default,
    YSP: require("../../../assets/images/ysp.png").default,
    Soul: require("../../../assets/images/soul.png").default,
    LingoTechAi: require("../../../assets/images/lingotech.png").default,
    Evium: require("../../../assets/images/evium.png").default,
    Installims: require("../../../assets/images/installims.png").default,
    Tandom: require("../../../assets/images/tandom.png").default,
    Swaaaad: require("../../../assets/images/swaaad-app.png").default,
    Troom: require("../../../assets/images/troom.png").default,
    WeAreOne:require("../../../assets/images/we-are-one.png").default,

}
const CONTACTUS = {
    MessengerGrey: require("../../../assets/images/messenger-grey.png").default,
    WhatsappGrey: require("../../../assets/images/whatsapp-grey.png").default,
    SkypeGrey: require("../../../assets/images/skype-grey.png").default,
    GmailGrey: require("../../../assets/images/gmail-grey.png").default,
}
const BLOG = {
    ChatGrey: require("../../../assets/images/chat-grey.png").default,
    InternetOfThings: require("../../../assets/images/internet-of-things.jpg").default,
    RightCompanyToJoin: require("../../../assets/images/right-company-to-join.jpg").default,
    StatisticsAndAnalytics: require("../../../assets/images/statistics-and-analytics.jpg").default,
    Blog1: require("../../../assets/images/blog-1.jpg").default,
    IotUse: require("../../../assets/images/iot-use.jpg").default,
    IotIndustryBannerUse: require("../../../assets/images/iot-industry-banner-use.jpg").default,
    IotUses: require("../../../assets/images/iot-uses.jpg").default,
    AreYouGoingTolearnSomethingnew: require("../../../assets/images/are-you-going-to-learn-something-new.jpg").default,
    BlogDemand:require("../../../assets/images/blog-demand.png").default,
    BlogEcommerce:require("../../../assets/images/blog-ecommerce-.png").default,
    BlogEducation:require("../../../assets/images/blog-education.png").default,
    BlogHealth:require("../../../assets/images/blog-health.png").default,
    // BlogFood:require("../../../assets/images/blog-food.gif").default,
    BlogBanking:require("../../../assets/images/blog-banking.png").default,
    PaginationArrowLeft:require("../../../assets/images/left-arrow-white.png").default,
    PaginationArrowRight:require("../../../assets/images/right-arrow-white.png").default,
    BlogEcommerce1:require("../../../assets/images/blogs/ecommerce-app-img-1.png").default,
    BlogEcommerce2:require("../../../assets/images/blogs/ecommerce-app-img-2.png").default,
    BlogEcommerce3:require("../../../assets/images/blogs/ecommerce-app-img-3.png").default,
    BlogEcommerce4:require("../../../assets/images/blogs/ecommerce-app-img-4.png").default,
}
const CAREER = {
    arrow:require("../../../assets/images/arrow-up-white.png").default,
}
const GALLERY= {
    Gallerybanner:require("../../../assets/images/gallery-banner.webp").default,
    gallerySlide1:require("../../../assets/images/galleryslide1.png").default,
    gallerySlide2:require("../../../assets/images/galleryslide2.png").default,
    gallerySlide3:require("../../../assets/images/galleryslide3.png").default,
    gallerySlide4:require("../../../assets/images/galleryslide4.png").default,

    memoriesimg1:require("../../../assets/images/memories-img7.png").default,
    memoriesimg2:require("../../../assets/images/memories-img2.png").default,
    memoriesimg3:require("../../../assets/images/memories-img3.png").default,
    memoriesimg4:require("../../../assets/images/memories-img4.png").default,
    memoriesimg5:require("../../../assets/images/memories-img1.png").default,
    memoriesimg6: require("../../../assets/images/memories-img6.png").default,
    memoriesimg7:require("../../../assets/images/gallery-img-1.jpeg").default,

    memoriesimg8:require("../../../assets/images/gallery-img-2.jpeg").default,
    memoriesimg9:require("../../../assets/images/gallery-img-3.jpeg").default,
    memoriesimg10:require("../../../assets/images/gallery-img-4.jpeg").default,
    memoriesimg11:require("../../../assets/images/gallery-img-5.jpeg").default,
    memoriesimg12:require("../../../assets/images/gallery-img-6.jpeg").default,
    memoriesimg13:require("../../../assets/images/gallery-img-7.jpeg").default,
    memoriesimg14:require("../../../assets/images/gallery-img-8.jpeg").default,
    memoriesimg15:require("../../../assets/images/gallery-img-9.jpeg").default,
    memoriesimg16:require("../../../assets/images/gallery-img-10.jpeg").default,
    memoriesimg17:require("../../../assets/images/gallery-img-11.jpeg").default,
    memoriesimg18:require("../../../assets/images/gallery-img-12.jpeg").default,
    memoriesimg19:require("../../../assets/images/gallery-img-13.jpeg").default,
    memoriesimg20:require("../../../assets/images/gallery-img-14.jpeg").default,
    memoriesimg21:require("../../../assets/images/gallery-img-15.jpeg").default,
    memoriesimg22:require("../../../assets/images/gallery-img-16.jpeg").default,
    memoriesimg23:require("../../../assets/images/gallery-img-17.jpeg").default,
    memoriesimg24:require("../../../assets/images/gallery-img-18.jpg").default,
    memoriesimg25:require("../../../assets/images/gallery-img-19.jpg").default,
    memoriesimg26:require("../../../assets/images/gallery-img-20.jpg").default,
    memoriesimg27:require("../../../assets/images/gallery-img-21.jpg").default,
    memoriesimg28:require("../../../assets/images/gallery-img-22.jpg").default,
    memoriesimg29:require("../../../assets/images/gallery-img-23.jpg").default,
    memoriesimg30:require("../../../assets/images/gallery-img-24.jpg").default,
    memoriesimg31:require("../../../assets/images/gallery-img-25.jpg").default,
    memoriesimg32:require("../../../assets/images/gallery-img-26.jpg").default,
    memoriesimg33:require("../../../assets/images/gallery-img-27.jpg").default,
    memoriesimg34:require("../../../assets/images/gallery-img-28.jpg").default,
    memoriesimg35:require("../../../assets/images/gallery-img-29.jpg").default,
    memoriesimg36:require("../../../assets/images/gallery-img-30.jpg").default,
    memoriesimg37:require("../../../assets/images/gallery-img-31.jpg").default,
    memoriesimg38: require("../../../assets/images/gallery-img-32.jpg").default,
    memoriesimg39: require("../../../assets/images/gallery-img-33.jpg").default,
    memoriesimg40:require("../../../assets/images/gallery-img-34.jpg").default,
    memoriesimg41:require("../../../assets/images/gallery-img-35.jpg").default,
    memoriesimg42:require("../../../assets/images/gallery-img-36.jpg").default,
    memoriesimg43:require("../../../assets/images/gallery-img-37.jpg").default,
    memoriesimg44:require("../../../assets/images/gallery-img-38.jpg").default,
    memoriesimg45:require("../../../assets/images/gallery-img-39.jpg").default,
    memoriesimg46:require("../../../assets/images/gallery-img-40.jpg").default,
    memoriesimg47:require("../../../assets/images/gallery-img-41.jpg").default,
    memoriesimg48:require("../../../assets/images/gallery-img-42.jpg").default,
    memoriesimg49:require("../../../assets/images/gallery-img-43.jpg").default,
    memoriesimg50:require("../../../assets/images/gallery-img-44.jpg").default,
    memoriesimg51:require("../../../assets/images/gallery-img-45.jpg").default,
    memoriesimg52: require("../../../assets/images/gallery-img-46.jpg").default,
    memoriesimg53:require("../../../assets/images/gallery-img-47.jpg").default,



}
const SEO = {
    DigitalMarketingDiscussion:require("../../../assets/images/digital-marketing-discussion.webp").default,
    SeoServiceBg:require("../../../assets/images/header-bg-half.png").default,
    SeoGirl:require("../../../assets/images/seo-girl.png").default,
    Elements:require("../../../assets/images/elements.png").default,
    Settings:require("../../../assets/images/settings.png").default,
    RootDirectory:require("../../../assets/images/root-directory.png").default,
    Review:require("../../../assets/images/review.png").default,
    WebsiteContent:require("../../../assets/images/website-content.png").default,
    Backlinks:require("../../../assets/images/backlinks.png").default,
    TwoManDiss:require("../../../assets/images/two-man-diss.jpg").default,
    // ThreeGirlDisc:require("../../../assets/images/three-girl-disc.png").default,
}
const TRIP = {
    HailHimalayas: require("../../../assets/images/hail-himalayas.jpg").default,
    HailHimalayasActivities: require("../../../assets/images/hail-himalayas-activities.webp").default,
    HailHimalayasDinningArea: require("../../../assets/images/hail-himalayas-dinning-area.webp").default,
    WaterFallImg1: require("../../../assets/images/water-fall-img-1.webp").default,
    WaterFallImg2: require("../../../assets/images/water-fall-img-2.webp").default,
    WaterFallImg3: require("../../../assets/images/water-fall-img-3.jpg").default,
    WaterFallImg5: require("../../../assets/images/water-fall-img-5.webp").default,
    WaterFallImg6: require("../../../assets/images/water-fall-img-6.jpg").default,
    WaterFallImg7: require("../../../assets/images/water-fall-img-7.jpg").default,
    WaterFallImg8: require("../../../assets/images/water-fall-img-8.jpg").default,
    GeekyFun1: require("../../../assets/images/geeky-fun-1.webp").default,
    GeekyFun2: require("../../../assets/images/geeky-fun-2.webp").default,
    GeekyFun3: require("../../../assets/images/geeky-fun-3.webp").default,
    GeekyFun4: require("../../../assets/images/geeky-fun-4.webp").default,
    Anniversary4: require("../../../assets/video/anniversary-4.mp4").default,
    anniversary4Cake: require("../../../assets/images/anniversary-4.jpg").default,
    AnniversaryCakeCutting: require("../../../assets/images/4-anniversary-cake-cutting.jpg").default,
    AugCelebration: require("../../../assets/images/15-aug-celebration.jpg").default,
    TeamParty: require("../../../assets/images/team-party.jpg").default,
}
const WEBDEVELOPMENT = {
    GirlWithRedBg: require("../../../assets/images/girl-with-red-bg.png").default,
    Messenger: require("../../../assets/images/messenger.png").default,
    Whatsapp: require("../../../assets/images/whatsapp.png").default,
    SkypeGrey: require("../../../assets/images/skype-grey.png").default,
    Gmail: require("../../../assets/images/gmail.png").default,
    NodeJs: require("../../../assets/images/nodejs.png").default,
    SymfonyBlack: require("../../../assets/images/symfony-black.png").default,
    Php: require("../../../assets/images/php.png").default,
    React: require("../../../assets/images/react.png").default,
    JavaWd: require("../../../assets/images/java-wd.png").default,
    Kotlin: require("../../../assets/images/kotlin.png").default,
    Upwork: require("../../../assets/images/up-work.png").default,
    Freelancer: require("../../../assets/images/freelancer.png").default,
}
const APPDETAILS  = {
    YellowMan: require("../../../assets/images/logo-yellow-man.webp").default,
    Mobile1: require("../../../assets/images/mobile-1.webp").default,
    Mobile2: require("../../../assets/images/mobile-2.webp").default,
    OrderFood: require("../../../assets/images/order-food.png").default,
    SmartPhone: require("../../../assets/images/smartphone.png").default,
    AppDetails: require("../../../assets/images/app-details.png").default,
    NodeJsImg:require("../../../assets/images/nodejs.png").default,
    SymfonyImg:require("../../../assets/images/symfony-services.png").default,
    PhpImg:require("../../../assets/images/php.png").default,
    ReactImg:require("../../../assets/images/react.png").default,
    KotlinImg:require("../../../assets/images/kotlin.png").default,
    JavaImg:require("../../../assets/images/java-wd.png").default,
    MavrikProject:require("../../../assets/images/mavrik-project-bg.png").default,
    AuslankmatrimonyProject:require("../../../assets/images/auslankmatrimony-project-bg.png").default,
    SportGearWesite:require("../../../assets/images/sport-gear-website.jpg").default,
    AllInProject:require("../../../assets/images/all-in-project.png").default,
    SportGearProject:require("../../../assets/images/sport-gear-project.png").default,
    FreshyProject:require("../../../assets/images/freshy-project.png").default,
    CandyCoinProject:require("../../../assets/images/candycoin-project.png").default,
    TadPoleProject:require("../../../assets/images/tadpole-project.png").default,
    Aws:require("../../../assets/images/aws.png").default,
    ElasticSearch:require("../../../assets/images/elastic-search.png").default,
    FabricJs:require("../../../assets/images/fabric.png").default,
    MySql:require("../../../assets/images/mysql.png").default,
    Wordpress:require("../../../assets/images/wordpress-logo-2.png").default,
    Gutenberg:require("../../../assets/images/Gutenberg-logo.png").default,
    NextJs:require("../../../assets/images/next-js.png").default,
    Next:require("../../../assets/images/nextjs.png").default,
    GraphQl:require("../../../assets/images/graph-ql.png").default,
    ExpressJs:require("../../../assets/images/Express-js.png").default,
    PostreSql:require("../../../assets/images/PostgreSQL-Logo.png").default,
    SportBaseball:require("../../../assets/images/sport-baseball.png").default,
    SportVolleyball:require("../../../assets/images/sport-volleyball.png").default,
    SportFootball:require("../../../assets/images/sport-football.png").default,
    SportBasketball:require("../../../assets/images/sport-basketball.png").default,
    RestApi:require("../../../assets/images/rest-api.png").default,
    SportHome:require("../../../assets/images/sport-home.png").default,
    MavrikHome:require("../../../assets/images/mavrik-home.jpg").default,
    MavrikAbout:require("../../../assets/images/mavrik-about.png").default,
    MavrikCase:require("../../../assets/images/mavrik-case.png").default,
    MavrikService:require("../../../assets/images/mavrik-service.png").default,
    MavrikContact:require("../../../assets/images/mavrik-contact.png").default,
    QualityApp1:require("../../../assets/images/quality-app-1.png").default,
    QualityApp2:require("../../../assets/images/quality-app-2.png").default,
    QualityApp3:require("../../../assets/images/quality-app-3.png").default,
    QualityApp4:require("../../../assets/images/quality-app-4.png").default,
    AllIn1:require("../../../assets/images/all-in-1.png").default,
    AllIn2:require("../../../assets/images/all-in-2.png").default,
    AllIn3:require("../../../assets/images/all-in-3.png").default,
    AllIn4:require("../../../assets/images/all-in-4.png").default,
    AllIn5:require("../../../assets/images/all-in-5.png").default,
    Freshy1:require("../../../assets/images/freshy-1.png").default,
    Freshy2:require("../../../assets/images/freshy-2.png").default,
    Freshy3:require("../../../assets/images/freshy-3.png").default,
    Freshy4:require("../../../assets/images/freshy-4.png").default,
    GoLoader:require("../../../assets/images/go-loder.png").default,
    VegatoBanner:require("../../../assets/images/vegato-banner.png").default,
    // MeetingManagmentBanner:require("../../../assets/images/360-meeting-managment-banner.png").default,
    RxTroBanner:require("../../../assets/images/rx-tro-banner.png").default,
    TadpoleBanner:require("../../../assets/images/tadpole-banner.png").default,
    FreshyBanner:require("../../../assets/images/freshy-banner.webp").default,
    // SideffectBanner:require("../../../assets/images/sideffect-banner.png").default,
    MeetingManagmentSlider:require("../../../assets/images/meeting-managment-1.png").default,
    MeetingManagmentSlider2:require("../../../assets/images/meeting-managment-2.png").default,
    MeetingManagmentSlider3:require("../../../assets/images/meeting-managment-3.png").default,
    MeetingManagmentSlider4:require("../../../assets/images/meeting-managment-4.png").default,
    FreshySlider1:require("../../../assets/images/freshy-mobile-1.png").default,
    FreshySlider2:require("../../../assets/images/freshy-mobile-2.png").default,
    FreshySlider3:require("../../../assets/images/freshy-mobile-3.png").default,
    FreshySlider4:require("../../../assets/images/freshy-mobile-4.png").default,
    TadpoleMobile1:require("../../../assets/images/tadpole-mobile-1.png").default,
    TadpoleMobile2:require("../../../assets/images/tadpole-mobile-2.png").default,
    TadpoleMobile3:require("../../../assets/images/tadpole-mobile-3.png").default,
    TadpoleMobile4:require("../../../assets/images/tadpole-mobile-4.png").default,
    RxTroMobile1:require("../../../assets/images/rxtro-mobile-1.png").default,
    RxTroMobile2:require("../../../assets/images/rxtro-mobile-2.png").default,
    RxTroMobile3:require("../../../assets/images/rxtro-mobile-3.png").default,
    RxTroMobile4:require("../../../assets/images/rxtro-mobile-4.png").default,
    SideffectMobile1:require("../../../assets/images/sideffect-mobile-1.png").default,
    SideffectMobile2:require("../../../assets/images/sideffect-mobile-2.png").default,
    SideffectMobile3:require("../../../assets/images/sideffect-mobile-3.png").default,
    VagetoMobile1:require("../../../assets/images/vageto-mobile-1.png").default,
    VagetoMobile2:require("../../../assets/images/vageto-mobile-2.png").default,
    VagetoMobile3:require("../../../assets/images/vageto-mobile-3.png").default,
    CandyCoin1:require("../../../assets/images/candy-1.png").default,
    CandyCoin2:require("../../../assets/images/candy-2.png").default,
    CandyCoin3:require("../../../assets/images/candy-3.png").default,
    QualityMindBanner:require("../../../assets/images/quality-mind-banner.png").default,
    AuslankamatrimonyWebsite1:require("../../../assets/images/auslankamatrimony-website-1.png").default,
    AuslankamatrimonyWebsite2:require("../../../assets/images/auslankamatrimony-website-2.png").default,
    AuslankamatrimonyWebsite3:require("../../../assets/images/auslankamatrimony-website-3.png").default,
    TadpoleRidesWebsite: require("../../../assets/images/tadpole-website.png").default,
    BodyDrenchWebsite: require("../../../assets/images/body-drench-website-2.png").default,
    BodyDrenchWebsite2: require("../../../assets/images/body-drench-website-3.png").default,
    BodyDrenchWebsite3:require("../../../assets/images/body-drench-website-1.png").default,
    CofaxWebsite: require("../../../assets/images/cofax-website-1.png").default,
    CofaxWebsite2: require("../../../assets/images/cofax-website-2.png").default,
    CofaxWebsite3: require("../../../assets/images/cofax-website-3.png").default,
    RiverEdgeWebsite: require("../../../assets/images/river-edge-website-1.png").default,
    RiverEdgeWebsite2: require("../../../assets/images/river-edge-website-2.png").default,
    RiverEdgeWebsite3: require("../../../assets/images/river-edge-website-3.png").default,
    FrontFootersWebsite: require("../../../assets/images/frontfooter-website-1.png").default,
    FrontFootersWebsite2: require("../../../assets/images/frontfooter-website-2.png").default,
    FrontFootersWebsite3: require("../../../assets/images/frontfooter-website-3.png").default,
    ElRanchoVistaWebsite: require("../../../assets/images/el-rancho-website.png").default,
    ElRanchoVistaWebsite2: require("../../../assets/images/el-rancho-website-2.png").default,
    ElRanchoVistaWebsite3: require("../../../assets/images/el-rancho-website-3.png").default,
    YspWebsite: require("../../../assets/images/ysp-website-1.png").default,
    YspWebsite2: require("../../../assets/images/ysp-website-2.png").default,
    YspWebsite3: require("../../../assets/images/ysp-website-3.png").default,
    LingoTechAIWebsite: require("../../../assets/images/lingotech-website-1.png").default,
    LingoTechAIWebsite2: require("../../../assets/images/lingotech-website-2.png").default,
    SoulWebsite: require("../../../assets/images/soulffy-website-1.png").default,
    SoulWebsite2: require("../../../assets/images/soulffy-website-2.png").default,
    SoulWebsite3: require("../../../assets/images/soulffy-website-3.png").default,
    EviumWebsite: require("../../../assets/images/evium-website-1.png").default,
    EviumWebsite2: require("../../../assets/images/evium-website-2.png").default,
    EviumWebsite3: require("../../../assets/images/evium-website-3.png").default,
    InstallimsWebsite: require("../../../assets/images/installims-website-1.png").default,
}


const CRICKETMATCHES  = {
    Grab:require("../../../assets/images/grab.png").default,
    Six:require("../../../assets/images/umpire.png").default,
    CricketLogic:require("../../../assets/images/field.png").default,
    NotOut:require("../../../assets/images/not-out.png").default,

    // Cricket1:require("../../../assets/images/cricket-4.jpeg"),
    // Cricket2:require("../../../assets/images/cricket-3.jpeg"),
    // Cricket3:require("../../../assets/images/cricket-7.jpeg"),
    // Cricket4:require("../../../assets/images/not-out.png"),


    Cricket1:require("../../../assets/images/cricket-2.webp").default,
    Cricket2:require("../../../assets/images/cricket-2.webp").default,
    Cricket3:require("../../../assets/images/cricket-3.webp").default,
    Cricket5:require("../../../assets/images/cricket-5.jpeg").default,
    Cricket7:require("../../../assets/images/cricket-7.jpeg").default,
    Cricket12:require("../../../assets/images/cricket-12.jpeg").default,
    Cricket15:require("../../../assets/images/cricket-15.jpg").default,
    Cricket16:require("../../../assets/images/gallery-img-28.jpg").default,
    Cricket17:require("../../../assets/images/gallery-img-19.jpg").default,
    Cricket18:require("../../../assets/images/gallery-img-34.jpg").default,
    Cricket19:require("../../../assets/images/gallery-img-27.jpg").default,
    Cricket20:require("../../../assets/images/gallery-img-25.jpg").default,
    Cricket21:require("../../../assets/images/gallery-img-24.jpg").default,
    Cricket22: require("../../../assets/images/gallery-img-23.jpg").default,
    
    Cricket23: require("../../../assets/images/gallery-img-22.jpg").default,
    Cricket24: require("../../../assets/images/gallery-img-21.jpg").default,
    Cricket25: require("../../../assets/images/gallery-img-28.jpg").default,
    Cricket26: require("../../../assets/images/gallery-img-34.jpg").default,
    
    CricketBottomBanner:require("../../../assets/images/bottom-banner.png").default,
    CricketClip: require("../../../assets/video/cricket-match-clip.mp4").default,
}

export const ASSETS = {
    COMMON,
    HOME,
    ABOUT,
    SERVICES,
    PORTFOLIO,
    CONTACTUS,
    BLOG,
    CAREER,
    GALLERY,
    SEO,
    TRIP,
    WEBDEVELOPMENT,
    APPDETAILS,
    CRICKETMATCHES
};
